### ISSUE TITLE
Why is this library not found on npm?

### ISSUE THREAD

**Issue by Dr-Harris** [sikozonpc/git-cli-parser#6]
npm ERR! 404 Not Found - GET https://registry.npmjs.com/node-git-parser - Not found
npm ERR! 404 
npm ERR! 404  'node-git-parser@latest' is not in the npm registry.

**Comment by sikozonpc** [comment]
@Dr-Harris  Hey, this package is currently not being developed anymore, if you need such, I think there might be a few if you search git-cli on google.

**Comment by Dr-Harris** [comment]
@sikozonpc Thank you.
